include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "android/**"
    - "ios/**"
    - "lib/generated/**"
    - "build/**"

  errors:
    missing_required_param: error
    missing_return: error
    unnecessary_getters_setters: error
    prefer_final_fields: error
    avoid_init_to_null: error
    unnecessary_null_comparison: error

linter:
  rules:
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - constant_identifier_names
    - control_flow_in_finally
    - empty_catches
    - empty_constructor_bodies
    - implementation_imports
    - iterable_contains_unrelated_type
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - non_constant_identifier_names
    - null_closures
    - override_on_non_overriding_member
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_is_empty
    - prefer_final_fields
    - slash_for_doc_comments
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_new
    - unrelated_type_equality_checks
    - valid_regexps